name: publish-modules

on:
  push:
    branches:
       - main
    paths:
      - 'modules/**'

permissions:
  id-token: write
  contenst: read


# jobs:
#   publish:
#     uses: ./.github/workflows/publish-module.yml
#     with:
#       path: 'modules/main.bicep'